vich_uploader:
    db_driver: orm

    mappings:
       pictures:
           uri_prefix: /user/pictures
           upload_destination: '%kernel.project_dir%/public/user/pictures'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer